spring.application.name=pi-control-centre
fast.metrics.collector.interval=2s
sensor.metrics.collector.interval=5s
slow.metrics.collector.interval=30s
spring.data.redis.host=localhost
spring.data.redis.port=6379